name: Publication CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Decode Signature
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SEC_RING_DECRYPT_PASSWORD }}" --output secring.gpg secring.gpg.gpg

      - name: Publish Maven Repository
        run: ./gradlew publishMavenPublicationToMavenRepository -Psigning.secretKeyRingFile=./secring.gpg -Psigning.password="${{ secrets.SEC_RING_PASSWORD }}" -Psigning.keyId="${{ secrets.SEC_RING_KEY_ID }}"
        if: "!contains(github.event.head_commit.message, '[publish skip]')"
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

      - name: Submit Publication
        if: "!contains(github.event.head_commit.message, '[publish skip]')"
        run: |
          curl --location --request POST 'https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/dev.forcetower' -u "${{ secrets.MAVEN_CENTRAL_USERNAME }}:${{ secrets.MAVEN_CENTRAL_PASSWORD }}"
